services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # backend
  api-gateway:
    build: ./backend/api-gateway
    container_name: api_gateway_container
    ports:
      - "5000:5000"
    volumes:
    - ./backend/api-gateway:/app
    - /app/node_modules
    env_file:
      - ./backend/api-gateway/.env
    environment:
      - AUTH_SERVICE=http://auth-service:5001
      - PRODUCT_SERVICE=http://product-service:5002
      - FAVORITE_SERVICE=http://favorite-service:5003
    depends_on:
      - auth-service
      - product-service
      - favorite-service
  auth-service:
    build: ./backend/auth-service
    container_name: auth_service_container
    ports:
      - "5001:5001"
    volumes:
    - ./backend/auth-service:/app
    - /app/node_modules
    env_file:
      - ./backend/auth-service/.env
    environment:
      - MONGO_URI=url_mongo_atlas
    depends_on:
      - mongo
  product-service:
    build: ./backend/product-service
    container_name: product_service_container
    ports:
      - "5002:5002"
    volumes:
    - ./backend/product-service:/app
    - /app/node_modules
    env_file:
      - ./backend/product-service/.env
    environment:
      - MONGO_URI=url_mongo_atlas
    depends_on:
      - mongo
  favorite-service:
    build: ./backend/favorite-service
    container_name: favorite_service_container
    ports:
      - "5003:5003"
    volumes:
    - ./backend/favorite-service:/app
    - /app/node_modules
    env_file:
      - ./backend/favorite-service/.env
    environment:
      - MONGO_URI=url_mongo_atlas
    depends_on:
      - mongo


  # frontend
  auth-frontend:
    build: ./frontend/auth-frontend
    container_name: auth_frontend_container
    ports:
      - "5173:5173"
    volumes:
    - ./frontend/auth-frontend:/app
    - /app/node_modules
    depends_on:
    - api-gateway
  product-frontend:
    build: ./frontend/product-frontend
    container_name: product_frontend_container
    ports:
      - "4200:4200"
    volumes:
    - ./frontend/product-frontend:/app
    - /app/node_modules
    depends_on:
    - api-gateway

volumes:
  mongo-data: